# Generated by Django 4.2.1 on 2023-06-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(unique=True)),
                ('limite_compras', models.IntegerField(max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('foto_cliente', models.ImageField(blank=True, null=True, upload_to='fotos_cliente/')),
            ],
        ),
    ]
