# Generated by Django 4.2.1 on 2023-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_compras',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
