# Generated by Django 4.2.1 on 2023-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_compras_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
