# Generated by Django 4.2 on 2023-05-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='camara_fria_quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
