# Generated by Django 4.2 on 2023-05-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_produto_camara_fria_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='camara_fria_quantidade',
            new_name='quantidade_na_camarafria',
        ),
    ]
