# Generated by Django 4.2 on 2023-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_rename_camara_fria_quantidade_produto_quantidade_na_camarafria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_atual_camarafria',
            field=models.IntegerField(default=0),
        ),
    ]
