# Generated by Django 4.2 on 2023-05-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
