# Generated by Django 4.2 on 2023-05-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_venda_total_venda_alter_venda_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
