# Generated by Django 4.2 on 2023-05-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0008_venda_preco_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], max_length=20),
        ),
    ]
