# Generated by Django 4.2 on 2023-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0010_alter_venda_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], max_length=20, null=True),
        ),
    ]
